gui:
  theme:
    activeBorderColor:
      - '#ffb3c1' # Light Pink
      - bold
    inactiveBorderColor:
      - '#9d8189'
    optionsTextColor:
      - '#b3e5fc' # Light Blue
    selectedLineBgColor:
      - '#5c2a38' # Deep Rose
    cherryPickedCommitBgColor:
      - '#9575cd'
    cherryPickedCommitFgColor:
      - '#ffb3c1'
    unstagedChangesColor:
      - '#ff5f7e' # Reddish-Pink
git:
  pagers:
    - pager: 'delta --dark --paging=never --minus-style="syntax #5c1520"
        --minus-emph-style="syntax #7a2030" --plus-style="syntax #1a4a28"
        --plus-emph-style="syntax #2d6b3e" --line-numbers
        --line-numbers-minus-style="#ffb3c1" --line-numbers-plus-style="#b4e1c1"
        --hyperlinks
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"'
