#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config window_placement second_child

# modify window shadows (default: on, options: on, off, float)
# example: show shadows only for floating windows
yabai -m config window_shadow float

# window opacity (default: off)
# example: render all unfocused windows with 90% opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95

# Removes the top bar
yabai -m config menubar_opacity 0.0

# Animations
yabai -m config window_animation_duration 0.2
yabai -m config window_animation_easing ease_out_quint

# Set all padding and gaps to 20pt (default: 0)
yabai -m config top_padding 15
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# on or off (default: off)
yabai -m config auto_balance off

# Floating point value between 0 and 1 (default: 0.5)
yabai -m config split_ratio 0.5

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# In case you want exceptions.
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add label="NordVPN" --add app="^NordVPN$" manage-off
yabai -m rule --add label="Tailscale" --add app="^Tailscale$" manage-off
yabai -m rule --add app="^(LuLu|Notes|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

# Borders Config
borders active_color=0xffffb7b2 inactive_color=0xff494d64 width=5.0 &

# Signals
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger window_focus"
# Auto-focus the first window when switching spaces
yabai -m signal --add event=space_changed action="yabai -m window --focus first 2>/dev/null"

# Config
yabai -m config layout bsp

# Finishing Text
echo "Yabai config loaded!"
