# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-fzf-links'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @treemux-tree-client 'neo-tree'
set -g @treemux-tree-nvim-init-file '~/.config/treemux/treemux_init.lua'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'schasse/tmux-jump'
set -g @plugin 'kiyoon/treemux'
set -g @plugin 'erikw/tmux-powerline'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Change the Prefix key
set -g prefix "C-Space"

set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'

# Enable mouse control for clicking tabs and dragging panes
set -g mouse on

# Allow programs in the pane to bypass tmux using terminal escape sequences
# BUG: Still kinda doesn't work with Kitty-Direct mode on FastFetch :(
# Extremely buggy.
# Kitty mode doesn't work entirely.
set -gq allow-passthrough on
set -g visual-activity off

# Force the tmux status bar background to be transparent
set-option -g status-style bg=default

# Pane border styling
set -g pane-border-style "fg=#7A738C"         # Muted gray for inactive panes
set -g pane-active-border-style "fg=#FFB7B2"  # Pastel pink for the active pane# Split panes using | and - and set the path to the current pane's path

# Delete Window
bind X confirm-before -p "kill-window #W? (y/n)" kill-window

# Splitting Windows
bind 'h' split-window -v -c "#{pane_current_path}"
bind 'v' split-window -h -c "#{pane_current_path}"

# Swapping panes
bind -n M-H swap-pane -d -t '{left-of}'
bind -n M-J swap-pane -d -t '{down-of}'
bind -n M-K swap-pane -d -t '{up-of}'
bind -n M-L swap-pane -d -t '{right-of}'

# Create Windows (Auto cd to current path)
bind c new-window -c "#{pane_current_path}"
# This one doesn't
bind M-c new-window -c "~"

# Go the most recent window
bind -n M-m last-window

# Move window left/right without dropping the prefix
bind-key -r S-Left swap-window -t -1\; select-window -t -1
bind-key -r S-Right swap-window -t +1\; select-window -t +1

# Enable repeatable window navigation
bind -r n next-window
bind -r p previous-window
# Amount of time to press the four above keys before you have to press <leader> again
set -g repeat-time 1500

# Auto rename
set -g renumber-windows on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
