# --- Base Colors ---
background            #171114
foreground            #F4EDEA
cursor                #FFB7B2
cursor_text_color     #1E1B22
selection_background  #493B47
selection_foreground  #F4EDEA

# --- 16-Color Palette ---
color0                #2A2734
color8                #7A738C
color1                #F28FAD
color9                #F8B0C4
color2                #A6D189
color10               #B5E890
color3                #F6C177
color11               #F9D092
color4                #96CDFB
color12               #B5DFFD
color5                #FFB7B2
color13               #FF8FA3
color6                #89DCEB
color14               #A6E3F4
color7                #E0DEF4
color15               #F4EDEA
