# Delete Window
bind X confirm-before -p "kill-window #W? (y/n)" kill-window
# Delete Window without confirmation
bind -r M-X kill-window

# Create Windows (Auto cd to current path)
bind -r c new-window -c "#{pane_current_path}"
# This one doesn't auto do
bind -r M-c new-window -c "~"

# Go the most recent window
bind -n M-m last-window

# Move window left/right without dropping the prefix
bind-key -r S-Left swap-window -t -1\; select-window -t -1
bind-key -r S-Right swap-window -t +1\; select-window -t +1

# Alt+n / Alt+p to switch windows without prefix
bind -n M-n next-window
bind -n M-p previous-window
unbind-key n
unbind-key p

# Reload
bind I source-file ~/.config/tmux/tmux.conf \; display-message "~/tmux.conf reloaded!"
